// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2a_p12
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_codegen.cpp:376


#include "DataExchangeC.h"
#include "tao/CDR.h"

#if !defined (__ACE_INLINE__)
#include "DataExchangeC.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_visitor_sequence\sequence_cs.cpp:73

#if !defined (_DATA_EXCHANGE_PLATFORM_PARAMLST_CS_)
#define _DATA_EXCHANGE_PLATFORM_PARAMLST_CS_

Data_Exchange_Platform::paramlst::paramlst (void)
{}

Data_Exchange_Platform::paramlst::paramlst (
    ::CORBA::ULong max)
  : ::TAO::unbounded_value_sequence<
        InterationParameter
      > (max)
{}

Data_Exchange_Platform::paramlst::paramlst (
    ::CORBA::ULong max,
    ::CORBA::ULong length,
    Data_Exchange_Platform::InterationParameter * buffer,
    ::CORBA::Boolean release
  )
  : ::TAO::unbounded_value_sequence<
        InterationParameter
      >
    (max, length, buffer, release)
{}

Data_Exchange_Platform::paramlst::paramlst (
    const paramlst &seq)
  : ::TAO::unbounded_value_sequence<
        InterationParameter
      > (seq)
{}

Data_Exchange_Platform::paramlst::~paramlst (void)
{}

#endif /* end #if !defined */

// TAO_IDL - Generated from
// e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_visitor_sequence\sequence_cs.cpp:73

#if !defined (_DATA_EXCHANGE_PLATFORM_INTERATIONLIST_CS_)
#define _DATA_EXCHANGE_PLATFORM_INTERATIONLIST_CS_

Data_Exchange_Platform::InterationList::InterationList (void)
{}

Data_Exchange_Platform::InterationList::InterationList (
    ::CORBA::ULong max)
  : ::TAO::unbounded_value_sequence<
        Interation
      > (max)
{}

Data_Exchange_Platform::InterationList::InterationList (
    ::CORBA::ULong max,
    ::CORBA::ULong length,
    Data_Exchange_Platform::Interation * buffer,
    ::CORBA::Boolean release
  )
  : ::TAO::unbounded_value_sequence<
        Interation
      >
    (max, length, buffer, release)
{}

Data_Exchange_Platform::InterationList::InterationList (
    const InterationList &seq)
  : ::TAO::unbounded_value_sequence<
        Interation
      > (seq)
{}

Data_Exchange_Platform::InterationList::~InterationList (void)
{}

#endif /* end #if !defined */

// TAO_IDL - Generated from
// e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_visitor_structure\cdr_op_cs.cpp:52

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const Data_Exchange_Platform::ObjectAttribute &_tao_aggregate)
{
  return
    (strm << _tao_aggregate.instanceName.in ()) &&
    (strm << _tao_aggregate.className.in ()) &&
    (strm << _tao_aggregate.attributeName.in ()) &&
    (strm << _tao_aggregate.attributeType.in ()) &&
    (strm << _tao_aggregate.attributeValue);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    Data_Exchange_Platform::ObjectAttribute &_tao_aggregate)
{
  return
    (strm >> _tao_aggregate.instanceName.out ()) &&
    (strm >> _tao_aggregate.className.out ()) &&
    (strm >> _tao_aggregate.attributeName.out ()) &&
    (strm >> _tao_aggregate.attributeType.out ()) &&
    (strm >> _tao_aggregate.attributeValue);
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_visitor_structure\cdr_op_cs.cpp:52

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const Data_Exchange_Platform::InterationParameter &_tao_aggregate)
{
  return
    (strm << _tao_aggregate.parameterName.in ()) &&
    (strm << _tao_aggregate.parameterType.in ()) &&
    (strm << _tao_aggregate.parameterValue);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    Data_Exchange_Platform::InterationParameter &_tao_aggregate)
{
  return
    (strm >> _tao_aggregate.parameterName.out ()) &&
    (strm >> _tao_aggregate.parameterType.out ()) &&
    (strm >> _tao_aggregate.parameterValue);
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_visitor_sequence\cdr_op_cs.cpp:96
#if !defined _TAO_CDR_OP_Data_Exchange_Platform_paramlst_CPP_
#define _TAO_CDR_OP_Data_Exchange_Platform_paramlst_CPP_

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const Data_Exchange_Platform::paramlst &_tao_sequence)
{
  return TAO::marshal_sequence(strm, _tao_sequence);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    Data_Exchange_Platform::paramlst &_tao_sequence)
{
  return TAO::demarshal_sequence(strm, _tao_sequence);
}


TAO_END_VERSIONED_NAMESPACE_DECL

#endif /* _TAO_CDR_OP_Data_Exchange_Platform_paramlst_CPP_ */

// TAO_IDL - Generated from
// e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_visitor_structure\cdr_op_cs.cpp:52

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const Data_Exchange_Platform::Interation &_tao_aggregate)
{
  return
    (strm << _tao_aggregate.timeStamp) &&
    (strm << _tao_aggregate.interationName.in ()) &&
    (strm << _tao_aggregate.parameterList);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    Data_Exchange_Platform::Interation &_tao_aggregate)
{
  return
    (strm >> _tao_aggregate.timeStamp) &&
    (strm >> _tao_aggregate.interationName.out ()) &&
    (strm >> _tao_aggregate.parameterList);
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_visitor_sequence\cdr_op_cs.cpp:96
#if !defined _TAO_CDR_OP_Data_Exchange_Platform_InterationList_CPP_
#define _TAO_CDR_OP_Data_Exchange_Platform_InterationList_CPP_

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const Data_Exchange_Platform::InterationList &_tao_sequence)
{
  return TAO::marshal_sequence(strm, _tao_sequence);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    Data_Exchange_Platform::InterationList &_tao_sequence)
{
  return TAO::demarshal_sequence(strm, _tao_sequence);
}


TAO_END_VERSIONED_NAMESPACE_DECL

#endif /* _TAO_CDR_OP_Data_Exchange_Platform_InterationList_CPP_ */

// TAO_IDL - Generated from
// e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_visitor_structure\cdr_op_cs.cpp:52

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const Data_Exchange_Platform::Interations &_tao_aggregate)
{
  return
    (strm << _tao_aggregate.timeStamp) &&
    (strm << _tao_aggregate.interationlst);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    Data_Exchange_Platform::Interations &_tao_aggregate)
{
  return
    (strm >> _tao_aggregate.timeStamp) &&
    (strm >> _tao_aggregate.interationlst);
}

TAO_END_VERSIONED_NAMESPACE_DECL



