// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2a_p12
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_codegen.cpp:376


#include "DataExchangeTypeSupportC.h"
#include "tao/CDR.h"
#include "ace/OS_NS_string.h"

#if !defined (__ACE_INLINE__)
#include "DataExchangeTypeSupportC.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_cs.cpp:51

// Traits specializations for Data_Exchange_Platform::ObjectAttributeTypeSupport.

Data_Exchange_Platform::ObjectAttributeTypeSupport_ptr
TAO::Objref_Traits<Data_Exchange_Platform::ObjectAttributeTypeSupport>::duplicate (
    Data_Exchange_Platform::ObjectAttributeTypeSupport_ptr p)
{
  return Data_Exchange_Platform::ObjectAttributeTypeSupport::_duplicate (p);
}

void
TAO::Objref_Traits<Data_Exchange_Platform::ObjectAttributeTypeSupport>::release (
    Data_Exchange_Platform::ObjectAttributeTypeSupport_ptr p)
{
  ::CORBA::release (p);
}

Data_Exchange_Platform::ObjectAttributeTypeSupport_ptr
TAO::Objref_Traits<Data_Exchange_Platform::ObjectAttributeTypeSupport>::nil (void)
{
  return Data_Exchange_Platform::ObjectAttributeTypeSupport::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<Data_Exchange_Platform::ObjectAttributeTypeSupport>::marshal (
    const Data_Exchange_Platform::ObjectAttributeTypeSupport_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

Data_Exchange_Platform::ObjectAttributeTypeSupport::ObjectAttributeTypeSupport (void)
{}

Data_Exchange_Platform::ObjectAttributeTypeSupport::~ObjectAttributeTypeSupport (void)
{
}

Data_Exchange_Platform::ObjectAttributeTypeSupport_ptr
Data_Exchange_Platform::ObjectAttributeTypeSupport::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return ObjectAttributeTypeSupport::_duplicate (
      dynamic_cast<ObjectAttributeTypeSupport_ptr> (_tao_objref)
    );
}

Data_Exchange_Platform::ObjectAttributeTypeSupport_ptr
Data_Exchange_Platform::ObjectAttributeTypeSupport::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return ObjectAttributeTypeSupport::_duplicate (
      dynamic_cast<ObjectAttributeTypeSupport_ptr> (_tao_objref)
    );
}

Data_Exchange_Platform::ObjectAttributeTypeSupport_ptr
Data_Exchange_Platform::ObjectAttributeTypeSupport::_nil (void)
{
  return 0;
}

Data_Exchange_Platform::ObjectAttributeTypeSupport_ptr
Data_Exchange_Platform::ObjectAttributeTypeSupport::_duplicate (ObjectAttributeTypeSupport_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
Data_Exchange_Platform::ObjectAttributeTypeSupport::_tao_release (ObjectAttributeTypeSupport_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
Data_Exchange_Platform::ObjectAttributeTypeSupport::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:Data_Exchange_Platform/ObjectAttributeTypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* Data_Exchange_Platform::ObjectAttributeTypeSupport::_interface_repository_id (void) const
{
  return "IDL:Data_Exchange_Platform/ObjectAttributeTypeSupport:1.0";
}

::CORBA::Boolean
Data_Exchange_Platform::ObjectAttributeTypeSupport::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_cs.cpp:51

// Traits specializations for Data_Exchange_Platform::ObjectAttributeDataWriter.

Data_Exchange_Platform::ObjectAttributeDataWriter_ptr
TAO::Objref_Traits<Data_Exchange_Platform::ObjectAttributeDataWriter>::duplicate (
    Data_Exchange_Platform::ObjectAttributeDataWriter_ptr p)
{
  return Data_Exchange_Platform::ObjectAttributeDataWriter::_duplicate (p);
}

void
TAO::Objref_Traits<Data_Exchange_Platform::ObjectAttributeDataWriter>::release (
    Data_Exchange_Platform::ObjectAttributeDataWriter_ptr p)
{
  ::CORBA::release (p);
}

Data_Exchange_Platform::ObjectAttributeDataWriter_ptr
TAO::Objref_Traits<Data_Exchange_Platform::ObjectAttributeDataWriter>::nil (void)
{
  return Data_Exchange_Platform::ObjectAttributeDataWriter::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<Data_Exchange_Platform::ObjectAttributeDataWriter>::marshal (
    const Data_Exchange_Platform::ObjectAttributeDataWriter_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

Data_Exchange_Platform::ObjectAttributeDataWriter::ObjectAttributeDataWriter (void)
{}

Data_Exchange_Platform::ObjectAttributeDataWriter::~ObjectAttributeDataWriter (void)
{
}

Data_Exchange_Platform::ObjectAttributeDataWriter_ptr
Data_Exchange_Platform::ObjectAttributeDataWriter::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return ObjectAttributeDataWriter::_duplicate (
      dynamic_cast<ObjectAttributeDataWriter_ptr> (_tao_objref)
    );
}

Data_Exchange_Platform::ObjectAttributeDataWriter_ptr
Data_Exchange_Platform::ObjectAttributeDataWriter::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return ObjectAttributeDataWriter::_duplicate (
      dynamic_cast<ObjectAttributeDataWriter_ptr> (_tao_objref)
    );
}

Data_Exchange_Platform::ObjectAttributeDataWriter_ptr
Data_Exchange_Platform::ObjectAttributeDataWriter::_nil (void)
{
  return 0;
}

Data_Exchange_Platform::ObjectAttributeDataWriter_ptr
Data_Exchange_Platform::ObjectAttributeDataWriter::_duplicate (ObjectAttributeDataWriter_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
Data_Exchange_Platform::ObjectAttributeDataWriter::_tao_release (ObjectAttributeDataWriter_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
Data_Exchange_Platform::ObjectAttributeDataWriter::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:Data_Exchange_Platform/ObjectAttributeDataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* Data_Exchange_Platform::ObjectAttributeDataWriter::_interface_repository_id (void) const
{
  return "IDL:Data_Exchange_Platform/ObjectAttributeDataWriter:1.0";
}

::CORBA::Boolean
Data_Exchange_Platform::ObjectAttributeDataWriter::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_cs.cpp:51

// Traits specializations for Data_Exchange_Platform::ObjectAttributeDataReader.

Data_Exchange_Platform::ObjectAttributeDataReader_ptr
TAO::Objref_Traits<Data_Exchange_Platform::ObjectAttributeDataReader>::duplicate (
    Data_Exchange_Platform::ObjectAttributeDataReader_ptr p)
{
  return Data_Exchange_Platform::ObjectAttributeDataReader::_duplicate (p);
}

void
TAO::Objref_Traits<Data_Exchange_Platform::ObjectAttributeDataReader>::release (
    Data_Exchange_Platform::ObjectAttributeDataReader_ptr p)
{
  ::CORBA::release (p);
}

Data_Exchange_Platform::ObjectAttributeDataReader_ptr
TAO::Objref_Traits<Data_Exchange_Platform::ObjectAttributeDataReader>::nil (void)
{
  return Data_Exchange_Platform::ObjectAttributeDataReader::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<Data_Exchange_Platform::ObjectAttributeDataReader>::marshal (
    const Data_Exchange_Platform::ObjectAttributeDataReader_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

Data_Exchange_Platform::ObjectAttributeDataReader::ObjectAttributeDataReader (void)
{}

Data_Exchange_Platform::ObjectAttributeDataReader::~ObjectAttributeDataReader (void)
{
}

Data_Exchange_Platform::ObjectAttributeDataReader_ptr
Data_Exchange_Platform::ObjectAttributeDataReader::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return ObjectAttributeDataReader::_duplicate (
      dynamic_cast<ObjectAttributeDataReader_ptr> (_tao_objref)
    );
}

Data_Exchange_Platform::ObjectAttributeDataReader_ptr
Data_Exchange_Platform::ObjectAttributeDataReader::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return ObjectAttributeDataReader::_duplicate (
      dynamic_cast<ObjectAttributeDataReader_ptr> (_tao_objref)
    );
}

Data_Exchange_Platform::ObjectAttributeDataReader_ptr
Data_Exchange_Platform::ObjectAttributeDataReader::_nil (void)
{
  return 0;
}

Data_Exchange_Platform::ObjectAttributeDataReader_ptr
Data_Exchange_Platform::ObjectAttributeDataReader::_duplicate (ObjectAttributeDataReader_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
Data_Exchange_Platform::ObjectAttributeDataReader::_tao_release (ObjectAttributeDataReader_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
Data_Exchange_Platform::ObjectAttributeDataReader::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/DataReaderEx:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:Data_Exchange_Platform/ObjectAttributeDataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* Data_Exchange_Platform::ObjectAttributeDataReader::_interface_repository_id (void) const
{
  return "IDL:Data_Exchange_Platform/ObjectAttributeDataReader:1.0";
}

::CORBA::Boolean
Data_Exchange_Platform::ObjectAttributeDataReader::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_cs.cpp:51

// Traits specializations for Data_Exchange_Platform::InterationParameterTypeSupport.

Data_Exchange_Platform::InterationParameterTypeSupport_ptr
TAO::Objref_Traits<Data_Exchange_Platform::InterationParameterTypeSupport>::duplicate (
    Data_Exchange_Platform::InterationParameterTypeSupport_ptr p)
{
  return Data_Exchange_Platform::InterationParameterTypeSupport::_duplicate (p);
}

void
TAO::Objref_Traits<Data_Exchange_Platform::InterationParameterTypeSupport>::release (
    Data_Exchange_Platform::InterationParameterTypeSupport_ptr p)
{
  ::CORBA::release (p);
}

Data_Exchange_Platform::InterationParameterTypeSupport_ptr
TAO::Objref_Traits<Data_Exchange_Platform::InterationParameterTypeSupport>::nil (void)
{
  return Data_Exchange_Platform::InterationParameterTypeSupport::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<Data_Exchange_Platform::InterationParameterTypeSupport>::marshal (
    const Data_Exchange_Platform::InterationParameterTypeSupport_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

Data_Exchange_Platform::InterationParameterTypeSupport::InterationParameterTypeSupport (void)
{}

Data_Exchange_Platform::InterationParameterTypeSupport::~InterationParameterTypeSupport (void)
{
}

Data_Exchange_Platform::InterationParameterTypeSupport_ptr
Data_Exchange_Platform::InterationParameterTypeSupport::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return InterationParameterTypeSupport::_duplicate (
      dynamic_cast<InterationParameterTypeSupport_ptr> (_tao_objref)
    );
}

Data_Exchange_Platform::InterationParameterTypeSupport_ptr
Data_Exchange_Platform::InterationParameterTypeSupport::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return InterationParameterTypeSupport::_duplicate (
      dynamic_cast<InterationParameterTypeSupport_ptr> (_tao_objref)
    );
}

Data_Exchange_Platform::InterationParameterTypeSupport_ptr
Data_Exchange_Platform::InterationParameterTypeSupport::_nil (void)
{
  return 0;
}

Data_Exchange_Platform::InterationParameterTypeSupport_ptr
Data_Exchange_Platform::InterationParameterTypeSupport::_duplicate (InterationParameterTypeSupport_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
Data_Exchange_Platform::InterationParameterTypeSupport::_tao_release (InterationParameterTypeSupport_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
Data_Exchange_Platform::InterationParameterTypeSupport::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:Data_Exchange_Platform/InterationParameterTypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* Data_Exchange_Platform::InterationParameterTypeSupport::_interface_repository_id (void) const
{
  return "IDL:Data_Exchange_Platform/InterationParameterTypeSupport:1.0";
}

::CORBA::Boolean
Data_Exchange_Platform::InterationParameterTypeSupport::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_cs.cpp:51

// Traits specializations for Data_Exchange_Platform::InterationParameterDataWriter.

Data_Exchange_Platform::InterationParameterDataWriter_ptr
TAO::Objref_Traits<Data_Exchange_Platform::InterationParameterDataWriter>::duplicate (
    Data_Exchange_Platform::InterationParameterDataWriter_ptr p)
{
  return Data_Exchange_Platform::InterationParameterDataWriter::_duplicate (p);
}

void
TAO::Objref_Traits<Data_Exchange_Platform::InterationParameterDataWriter>::release (
    Data_Exchange_Platform::InterationParameterDataWriter_ptr p)
{
  ::CORBA::release (p);
}

Data_Exchange_Platform::InterationParameterDataWriter_ptr
TAO::Objref_Traits<Data_Exchange_Platform::InterationParameterDataWriter>::nil (void)
{
  return Data_Exchange_Platform::InterationParameterDataWriter::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<Data_Exchange_Platform::InterationParameterDataWriter>::marshal (
    const Data_Exchange_Platform::InterationParameterDataWriter_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

Data_Exchange_Platform::InterationParameterDataWriter::InterationParameterDataWriter (void)
{}

Data_Exchange_Platform::InterationParameterDataWriter::~InterationParameterDataWriter (void)
{
}

Data_Exchange_Platform::InterationParameterDataWriter_ptr
Data_Exchange_Platform::InterationParameterDataWriter::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return InterationParameterDataWriter::_duplicate (
      dynamic_cast<InterationParameterDataWriter_ptr> (_tao_objref)
    );
}

Data_Exchange_Platform::InterationParameterDataWriter_ptr
Data_Exchange_Platform::InterationParameterDataWriter::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return InterationParameterDataWriter::_duplicate (
      dynamic_cast<InterationParameterDataWriter_ptr> (_tao_objref)
    );
}

Data_Exchange_Platform::InterationParameterDataWriter_ptr
Data_Exchange_Platform::InterationParameterDataWriter::_nil (void)
{
  return 0;
}

Data_Exchange_Platform::InterationParameterDataWriter_ptr
Data_Exchange_Platform::InterationParameterDataWriter::_duplicate (InterationParameterDataWriter_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
Data_Exchange_Platform::InterationParameterDataWriter::_tao_release (InterationParameterDataWriter_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
Data_Exchange_Platform::InterationParameterDataWriter::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:Data_Exchange_Platform/InterationParameterDataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* Data_Exchange_Platform::InterationParameterDataWriter::_interface_repository_id (void) const
{
  return "IDL:Data_Exchange_Platform/InterationParameterDataWriter:1.0";
}

::CORBA::Boolean
Data_Exchange_Platform::InterationParameterDataWriter::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_cs.cpp:51

// Traits specializations for Data_Exchange_Platform::InterationParameterDataReader.

Data_Exchange_Platform::InterationParameterDataReader_ptr
TAO::Objref_Traits<Data_Exchange_Platform::InterationParameterDataReader>::duplicate (
    Data_Exchange_Platform::InterationParameterDataReader_ptr p)
{
  return Data_Exchange_Platform::InterationParameterDataReader::_duplicate (p);
}

void
TAO::Objref_Traits<Data_Exchange_Platform::InterationParameterDataReader>::release (
    Data_Exchange_Platform::InterationParameterDataReader_ptr p)
{
  ::CORBA::release (p);
}

Data_Exchange_Platform::InterationParameterDataReader_ptr
TAO::Objref_Traits<Data_Exchange_Platform::InterationParameterDataReader>::nil (void)
{
  return Data_Exchange_Platform::InterationParameterDataReader::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<Data_Exchange_Platform::InterationParameterDataReader>::marshal (
    const Data_Exchange_Platform::InterationParameterDataReader_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

Data_Exchange_Platform::InterationParameterDataReader::InterationParameterDataReader (void)
{}

Data_Exchange_Platform::InterationParameterDataReader::~InterationParameterDataReader (void)
{
}

Data_Exchange_Platform::InterationParameterDataReader_ptr
Data_Exchange_Platform::InterationParameterDataReader::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return InterationParameterDataReader::_duplicate (
      dynamic_cast<InterationParameterDataReader_ptr> (_tao_objref)
    );
}

Data_Exchange_Platform::InterationParameterDataReader_ptr
Data_Exchange_Platform::InterationParameterDataReader::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return InterationParameterDataReader::_duplicate (
      dynamic_cast<InterationParameterDataReader_ptr> (_tao_objref)
    );
}

Data_Exchange_Platform::InterationParameterDataReader_ptr
Data_Exchange_Platform::InterationParameterDataReader::_nil (void)
{
  return 0;
}

Data_Exchange_Platform::InterationParameterDataReader_ptr
Data_Exchange_Platform::InterationParameterDataReader::_duplicate (InterationParameterDataReader_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
Data_Exchange_Platform::InterationParameterDataReader::_tao_release (InterationParameterDataReader_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
Data_Exchange_Platform::InterationParameterDataReader::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/DataReaderEx:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:Data_Exchange_Platform/InterationParameterDataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* Data_Exchange_Platform::InterationParameterDataReader::_interface_repository_id (void) const
{
  return "IDL:Data_Exchange_Platform/InterationParameterDataReader:1.0";
}

::CORBA::Boolean
Data_Exchange_Platform::InterationParameterDataReader::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_cs.cpp:51

// Traits specializations for Data_Exchange_Platform::InterationTypeSupport.

Data_Exchange_Platform::InterationTypeSupport_ptr
TAO::Objref_Traits<Data_Exchange_Platform::InterationTypeSupport>::duplicate (
    Data_Exchange_Platform::InterationTypeSupport_ptr p)
{
  return Data_Exchange_Platform::InterationTypeSupport::_duplicate (p);
}

void
TAO::Objref_Traits<Data_Exchange_Platform::InterationTypeSupport>::release (
    Data_Exchange_Platform::InterationTypeSupport_ptr p)
{
  ::CORBA::release (p);
}

Data_Exchange_Platform::InterationTypeSupport_ptr
TAO::Objref_Traits<Data_Exchange_Platform::InterationTypeSupport>::nil (void)
{
  return Data_Exchange_Platform::InterationTypeSupport::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<Data_Exchange_Platform::InterationTypeSupport>::marshal (
    const Data_Exchange_Platform::InterationTypeSupport_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

Data_Exchange_Platform::InterationTypeSupport::InterationTypeSupport (void)
{}

Data_Exchange_Platform::InterationTypeSupport::~InterationTypeSupport (void)
{
}

Data_Exchange_Platform::InterationTypeSupport_ptr
Data_Exchange_Platform::InterationTypeSupport::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return InterationTypeSupport::_duplicate (
      dynamic_cast<InterationTypeSupport_ptr> (_tao_objref)
    );
}

Data_Exchange_Platform::InterationTypeSupport_ptr
Data_Exchange_Platform::InterationTypeSupport::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return InterationTypeSupport::_duplicate (
      dynamic_cast<InterationTypeSupport_ptr> (_tao_objref)
    );
}

Data_Exchange_Platform::InterationTypeSupport_ptr
Data_Exchange_Platform::InterationTypeSupport::_nil (void)
{
  return 0;
}

Data_Exchange_Platform::InterationTypeSupport_ptr
Data_Exchange_Platform::InterationTypeSupport::_duplicate (InterationTypeSupport_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
Data_Exchange_Platform::InterationTypeSupport::_tao_release (InterationTypeSupport_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
Data_Exchange_Platform::InterationTypeSupport::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:Data_Exchange_Platform/InterationTypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* Data_Exchange_Platform::InterationTypeSupport::_interface_repository_id (void) const
{
  return "IDL:Data_Exchange_Platform/InterationTypeSupport:1.0";
}

::CORBA::Boolean
Data_Exchange_Platform::InterationTypeSupport::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_cs.cpp:51

// Traits specializations for Data_Exchange_Platform::InterationDataWriter.

Data_Exchange_Platform::InterationDataWriter_ptr
TAO::Objref_Traits<Data_Exchange_Platform::InterationDataWriter>::duplicate (
    Data_Exchange_Platform::InterationDataWriter_ptr p)
{
  return Data_Exchange_Platform::InterationDataWriter::_duplicate (p);
}

void
TAO::Objref_Traits<Data_Exchange_Platform::InterationDataWriter>::release (
    Data_Exchange_Platform::InterationDataWriter_ptr p)
{
  ::CORBA::release (p);
}

Data_Exchange_Platform::InterationDataWriter_ptr
TAO::Objref_Traits<Data_Exchange_Platform::InterationDataWriter>::nil (void)
{
  return Data_Exchange_Platform::InterationDataWriter::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<Data_Exchange_Platform::InterationDataWriter>::marshal (
    const Data_Exchange_Platform::InterationDataWriter_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

Data_Exchange_Platform::InterationDataWriter::InterationDataWriter (void)
{}

Data_Exchange_Platform::InterationDataWriter::~InterationDataWriter (void)
{
}

Data_Exchange_Platform::InterationDataWriter_ptr
Data_Exchange_Platform::InterationDataWriter::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return InterationDataWriter::_duplicate (
      dynamic_cast<InterationDataWriter_ptr> (_tao_objref)
    );
}

Data_Exchange_Platform::InterationDataWriter_ptr
Data_Exchange_Platform::InterationDataWriter::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return InterationDataWriter::_duplicate (
      dynamic_cast<InterationDataWriter_ptr> (_tao_objref)
    );
}

Data_Exchange_Platform::InterationDataWriter_ptr
Data_Exchange_Platform::InterationDataWriter::_nil (void)
{
  return 0;
}

Data_Exchange_Platform::InterationDataWriter_ptr
Data_Exchange_Platform::InterationDataWriter::_duplicate (InterationDataWriter_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
Data_Exchange_Platform::InterationDataWriter::_tao_release (InterationDataWriter_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
Data_Exchange_Platform::InterationDataWriter::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:Data_Exchange_Platform/InterationDataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* Data_Exchange_Platform::InterationDataWriter::_interface_repository_id (void) const
{
  return "IDL:Data_Exchange_Platform/InterationDataWriter:1.0";
}

::CORBA::Boolean
Data_Exchange_Platform::InterationDataWriter::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_cs.cpp:51

// Traits specializations for Data_Exchange_Platform::InterationDataReader.

Data_Exchange_Platform::InterationDataReader_ptr
TAO::Objref_Traits<Data_Exchange_Platform::InterationDataReader>::duplicate (
    Data_Exchange_Platform::InterationDataReader_ptr p)
{
  return Data_Exchange_Platform::InterationDataReader::_duplicate (p);
}

void
TAO::Objref_Traits<Data_Exchange_Platform::InterationDataReader>::release (
    Data_Exchange_Platform::InterationDataReader_ptr p)
{
  ::CORBA::release (p);
}

Data_Exchange_Platform::InterationDataReader_ptr
TAO::Objref_Traits<Data_Exchange_Platform::InterationDataReader>::nil (void)
{
  return Data_Exchange_Platform::InterationDataReader::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<Data_Exchange_Platform::InterationDataReader>::marshal (
    const Data_Exchange_Platform::InterationDataReader_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

Data_Exchange_Platform::InterationDataReader::InterationDataReader (void)
{}

Data_Exchange_Platform::InterationDataReader::~InterationDataReader (void)
{
}

Data_Exchange_Platform::InterationDataReader_ptr
Data_Exchange_Platform::InterationDataReader::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return InterationDataReader::_duplicate (
      dynamic_cast<InterationDataReader_ptr> (_tao_objref)
    );
}

Data_Exchange_Platform::InterationDataReader_ptr
Data_Exchange_Platform::InterationDataReader::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return InterationDataReader::_duplicate (
      dynamic_cast<InterationDataReader_ptr> (_tao_objref)
    );
}

Data_Exchange_Platform::InterationDataReader_ptr
Data_Exchange_Platform::InterationDataReader::_nil (void)
{
  return 0;
}

Data_Exchange_Platform::InterationDataReader_ptr
Data_Exchange_Platform::InterationDataReader::_duplicate (InterationDataReader_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
Data_Exchange_Platform::InterationDataReader::_tao_release (InterationDataReader_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
Data_Exchange_Platform::InterationDataReader::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/DataReaderEx:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:Data_Exchange_Platform/InterationDataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* Data_Exchange_Platform::InterationDataReader::_interface_repository_id (void) const
{
  return "IDL:Data_Exchange_Platform/InterationDataReader:1.0";
}

::CORBA::Boolean
Data_Exchange_Platform::InterationDataReader::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_cs.cpp:51

// Traits specializations for Data_Exchange_Platform::InterationsTypeSupport.

Data_Exchange_Platform::InterationsTypeSupport_ptr
TAO::Objref_Traits<Data_Exchange_Platform::InterationsTypeSupport>::duplicate (
    Data_Exchange_Platform::InterationsTypeSupport_ptr p)
{
  return Data_Exchange_Platform::InterationsTypeSupport::_duplicate (p);
}

void
TAO::Objref_Traits<Data_Exchange_Platform::InterationsTypeSupport>::release (
    Data_Exchange_Platform::InterationsTypeSupport_ptr p)
{
  ::CORBA::release (p);
}

Data_Exchange_Platform::InterationsTypeSupport_ptr
TAO::Objref_Traits<Data_Exchange_Platform::InterationsTypeSupport>::nil (void)
{
  return Data_Exchange_Platform::InterationsTypeSupport::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<Data_Exchange_Platform::InterationsTypeSupport>::marshal (
    const Data_Exchange_Platform::InterationsTypeSupport_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

Data_Exchange_Platform::InterationsTypeSupport::InterationsTypeSupport (void)
{}

Data_Exchange_Platform::InterationsTypeSupport::~InterationsTypeSupport (void)
{
}

Data_Exchange_Platform::InterationsTypeSupport_ptr
Data_Exchange_Platform::InterationsTypeSupport::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return InterationsTypeSupport::_duplicate (
      dynamic_cast<InterationsTypeSupport_ptr> (_tao_objref)
    );
}

Data_Exchange_Platform::InterationsTypeSupport_ptr
Data_Exchange_Platform::InterationsTypeSupport::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return InterationsTypeSupport::_duplicate (
      dynamic_cast<InterationsTypeSupport_ptr> (_tao_objref)
    );
}

Data_Exchange_Platform::InterationsTypeSupport_ptr
Data_Exchange_Platform::InterationsTypeSupport::_nil (void)
{
  return 0;
}

Data_Exchange_Platform::InterationsTypeSupport_ptr
Data_Exchange_Platform::InterationsTypeSupport::_duplicate (InterationsTypeSupport_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
Data_Exchange_Platform::InterationsTypeSupport::_tao_release (InterationsTypeSupport_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
Data_Exchange_Platform::InterationsTypeSupport::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:Data_Exchange_Platform/InterationsTypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* Data_Exchange_Platform::InterationsTypeSupport::_interface_repository_id (void) const
{
  return "IDL:Data_Exchange_Platform/InterationsTypeSupport:1.0";
}

::CORBA::Boolean
Data_Exchange_Platform::InterationsTypeSupport::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_cs.cpp:51

// Traits specializations for Data_Exchange_Platform::InterationsDataWriter.

Data_Exchange_Platform::InterationsDataWriter_ptr
TAO::Objref_Traits<Data_Exchange_Platform::InterationsDataWriter>::duplicate (
    Data_Exchange_Platform::InterationsDataWriter_ptr p)
{
  return Data_Exchange_Platform::InterationsDataWriter::_duplicate (p);
}

void
TAO::Objref_Traits<Data_Exchange_Platform::InterationsDataWriter>::release (
    Data_Exchange_Platform::InterationsDataWriter_ptr p)
{
  ::CORBA::release (p);
}

Data_Exchange_Platform::InterationsDataWriter_ptr
TAO::Objref_Traits<Data_Exchange_Platform::InterationsDataWriter>::nil (void)
{
  return Data_Exchange_Platform::InterationsDataWriter::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<Data_Exchange_Platform::InterationsDataWriter>::marshal (
    const Data_Exchange_Platform::InterationsDataWriter_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

Data_Exchange_Platform::InterationsDataWriter::InterationsDataWriter (void)
{}

Data_Exchange_Platform::InterationsDataWriter::~InterationsDataWriter (void)
{
}

Data_Exchange_Platform::InterationsDataWriter_ptr
Data_Exchange_Platform::InterationsDataWriter::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return InterationsDataWriter::_duplicate (
      dynamic_cast<InterationsDataWriter_ptr> (_tao_objref)
    );
}

Data_Exchange_Platform::InterationsDataWriter_ptr
Data_Exchange_Platform::InterationsDataWriter::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return InterationsDataWriter::_duplicate (
      dynamic_cast<InterationsDataWriter_ptr> (_tao_objref)
    );
}

Data_Exchange_Platform::InterationsDataWriter_ptr
Data_Exchange_Platform::InterationsDataWriter::_nil (void)
{
  return 0;
}

Data_Exchange_Platform::InterationsDataWriter_ptr
Data_Exchange_Platform::InterationsDataWriter::_duplicate (InterationsDataWriter_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
Data_Exchange_Platform::InterationsDataWriter::_tao_release (InterationsDataWriter_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
Data_Exchange_Platform::InterationsDataWriter::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:Data_Exchange_Platform/InterationsDataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* Data_Exchange_Platform::InterationsDataWriter::_interface_repository_id (void) const
{
  return "IDL:Data_Exchange_Platform/InterationsDataWriter:1.0";
}

::CORBA::Boolean
Data_Exchange_Platform::InterationsDataWriter::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_cs.cpp:51

// Traits specializations for Data_Exchange_Platform::InterationsDataReader.

Data_Exchange_Platform::InterationsDataReader_ptr
TAO::Objref_Traits<Data_Exchange_Platform::InterationsDataReader>::duplicate (
    Data_Exchange_Platform::InterationsDataReader_ptr p)
{
  return Data_Exchange_Platform::InterationsDataReader::_duplicate (p);
}

void
TAO::Objref_Traits<Data_Exchange_Platform::InterationsDataReader>::release (
    Data_Exchange_Platform::InterationsDataReader_ptr p)
{
  ::CORBA::release (p);
}

Data_Exchange_Platform::InterationsDataReader_ptr
TAO::Objref_Traits<Data_Exchange_Platform::InterationsDataReader>::nil (void)
{
  return Data_Exchange_Platform::InterationsDataReader::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<Data_Exchange_Platform::InterationsDataReader>::marshal (
    const Data_Exchange_Platform::InterationsDataReader_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

Data_Exchange_Platform::InterationsDataReader::InterationsDataReader (void)
{}

Data_Exchange_Platform::InterationsDataReader::~InterationsDataReader (void)
{
}

Data_Exchange_Platform::InterationsDataReader_ptr
Data_Exchange_Platform::InterationsDataReader::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return InterationsDataReader::_duplicate (
      dynamic_cast<InterationsDataReader_ptr> (_tao_objref)
    );
}

Data_Exchange_Platform::InterationsDataReader_ptr
Data_Exchange_Platform::InterationsDataReader::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return InterationsDataReader::_duplicate (
      dynamic_cast<InterationsDataReader_ptr> (_tao_objref)
    );
}

Data_Exchange_Platform::InterationsDataReader_ptr
Data_Exchange_Platform::InterationsDataReader::_nil (void)
{
  return 0;
}

Data_Exchange_Platform::InterationsDataReader_ptr
Data_Exchange_Platform::InterationsDataReader::_duplicate (InterationsDataReader_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
Data_Exchange_Platform::InterationsDataReader::_tao_release (InterationsDataReader_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
Data_Exchange_Platform::InterationsDataReader::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/DataReaderEx:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:Data_Exchange_Platform/InterationsDataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* Data_Exchange_Platform::InterationsDataReader::_interface_repository_id (void) const
{
  return "IDL:Data_Exchange_Platform/InterationsDataReader:1.0";
}

::CORBA::Boolean
Data_Exchange_Platform::InterationsDataReader::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

