// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2a_p12
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_codegen.cpp:152

#ifndef _TAO_IDL_DATAEXCHANGETYPESUPPORTC_TLG8IT_H_
#define _TAO_IDL_DATAEXCHANGETYPESUPPORTC_TLG8IT_H_

#include /**/ "ace/pre.h"


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include "tao/ORB.h"
#include "tao/SystemException.h"
#include "tao/Basic_Types.h"
#include "tao/ORB_Constants.h"
#include "dds/DCPS/ZeroCopyInfoSeq_T.h"
#include "dds/DCPS/ZeroCopySeq_T.h"
#include "tao/Object.h"
#include "tao/String_Manager_T.h"
#include "tao/Sequence_T.h"
#include "tao/Objref_VarOut_T.h"
#include "tao/Seq_Var_T.h"
#include "tao/Seq_Out_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#include "DataExchangeC.h"
#include "dds/DdsDcpsInfrastructureC.h"
#include "dds/DdsDcpsPublicationC.h"
#include "dds/DdsDcpsSubscriptionExtC.h"
#include "dds/DdsDcpsTopicC.h"
#include "dds/DdsDcpsTypeSupportExtC.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 2 || TAO_BETA_VERSION != 0
#error This file should be regenerated with TAO_IDL
#endif

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO 

// TAO_IDL - Generated from
// e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_visitor_module\module_ch.cpp:38

namespace Data_Exchange_Platform
{

  // TAO_IDL - Generated from
  // e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_visitor_sequence\sequence_ch.cpp:102

  typedef ::TAO::DCPS::ZeroCopyDataSeq< Data_Exchange_Platform::ObjectAttribute, DCPS_ZERO_COPY_SEQ_DEFAULT_SIZE> ObjectAttributeSeq;
  

  // TAO_IDL - Generated from
  // e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_interface.cpp:751

#if !defined (_DATA_EXCHANGE_PLATFORM_OBJECTATTRIBUTETYPESUPPORT__VAR_OUT_CH_)
#define _DATA_EXCHANGE_PLATFORM_OBJECTATTRIBUTETYPESUPPORT__VAR_OUT_CH_

  class ObjectAttributeTypeSupport;
  typedef ObjectAttributeTypeSupport *ObjectAttributeTypeSupport_ptr;

  typedef
    TAO_Objref_Var_T<
        ObjectAttributeTypeSupport
      >
    ObjectAttributeTypeSupport_var;
  
  typedef
    TAO_Objref_Out_T<
        ObjectAttributeTypeSupport
      >
    ObjectAttributeTypeSupport_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:43

  class  ObjectAttributeTypeSupport
    : public virtual ::OpenDDS::DCPS::TypeSupport
  
  {
  public:

    // TAO_IDL - Generated from
    // e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_type.cpp:307

    typedef ObjectAttributeTypeSupport_ptr _ptr_type;
    typedef ObjectAttributeTypeSupport_var _var_type;
    typedef ObjectAttributeTypeSupport_out _out_type;

    // The static operations.
    static ObjectAttributeTypeSupport_ptr _duplicate (ObjectAttributeTypeSupport_ptr obj);

    static void _tao_release (ObjectAttributeTypeSupport_ptr obj);

    static ObjectAttributeTypeSupport_ptr _narrow (::CORBA::Object_ptr obj);
    static ObjectAttributeTypeSupport_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static ObjectAttributeTypeSupport_ptr _nil (void);

    // TAO_IDL - Generated from
    // e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    ObjectAttributeTypeSupport (void);

    

    virtual ~ObjectAttributeTypeSupport (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    ObjectAttributeTypeSupport (const ObjectAttributeTypeSupport &);

    void operator= (const ObjectAttributeTypeSupport &);
  };

  // TAO_IDL - Generated from
  // e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_interface.cpp:751

#if !defined (_DATA_EXCHANGE_PLATFORM_OBJECTATTRIBUTEDATAWRITER__VAR_OUT_CH_)
#define _DATA_EXCHANGE_PLATFORM_OBJECTATTRIBUTEDATAWRITER__VAR_OUT_CH_

  class ObjectAttributeDataWriter;
  typedef ObjectAttributeDataWriter *ObjectAttributeDataWriter_ptr;

  typedef
    TAO_Objref_Var_T<
        ObjectAttributeDataWriter
      >
    ObjectAttributeDataWriter_var;
  
  typedef
    TAO_Objref_Out_T<
        ObjectAttributeDataWriter
      >
    ObjectAttributeDataWriter_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:43

  class  ObjectAttributeDataWriter
    : public virtual ::DDS::DataWriter
  
  {
  public:

    // TAO_IDL - Generated from
    // e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_type.cpp:307

    typedef ObjectAttributeDataWriter_ptr _ptr_type;
    typedef ObjectAttributeDataWriter_var _var_type;
    typedef ObjectAttributeDataWriter_out _out_type;

    // The static operations.
    static ObjectAttributeDataWriter_ptr _duplicate (ObjectAttributeDataWriter_ptr obj);

    static void _tao_release (ObjectAttributeDataWriter_ptr obj);

    static ObjectAttributeDataWriter_ptr _narrow (::CORBA::Object_ptr obj);
    static ObjectAttributeDataWriter_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static ObjectAttributeDataWriter_ptr _nil (void);

    virtual ::DDS::InstanceHandle_t register_instance (
      const ::Data_Exchange_Platform::ObjectAttribute & instance) = 0;

    virtual ::DDS::InstanceHandle_t register_instance_w_timestamp (
      const ::Data_Exchange_Platform::ObjectAttribute & instance,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance (
      const ::Data_Exchange_Platform::ObjectAttribute & instance,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance_w_timestamp (
      const ::Data_Exchange_Platform::ObjectAttribute & instance,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t write (
      const ::Data_Exchange_Platform::ObjectAttribute & instance_data,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t write_w_timestamp (
      const ::Data_Exchange_Platform::ObjectAttribute & instance_data,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t dispose (
      const ::Data_Exchange_Platform::ObjectAttribute & instance_data,
      ::DDS::InstanceHandle_t instance_handle) = 0;

    virtual ::DDS::ReturnCode_t dispose_w_timestamp (
      const ::Data_Exchange_Platform::ObjectAttribute & instance_data,
      ::DDS::InstanceHandle_t instance_handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::Data_Exchange_Platform::ObjectAttribute & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::Data_Exchange_Platform::ObjectAttribute & instance_data) = 0;

    // TAO_IDL - Generated from
    // e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    ObjectAttributeDataWriter (void);

    

    virtual ~ObjectAttributeDataWriter (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    ObjectAttributeDataWriter (const ObjectAttributeDataWriter &);

    void operator= (const ObjectAttributeDataWriter &);
  };

  // TAO_IDL - Generated from
  // e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_interface.cpp:751

#if !defined (_DATA_EXCHANGE_PLATFORM_OBJECTATTRIBUTEDATAREADER__VAR_OUT_CH_)
#define _DATA_EXCHANGE_PLATFORM_OBJECTATTRIBUTEDATAREADER__VAR_OUT_CH_

  class ObjectAttributeDataReader;
  typedef ObjectAttributeDataReader *ObjectAttributeDataReader_ptr;

  typedef
    TAO_Objref_Var_T<
        ObjectAttributeDataReader
      >
    ObjectAttributeDataReader_var;
  
  typedef
    TAO_Objref_Out_T<
        ObjectAttributeDataReader
      >
    ObjectAttributeDataReader_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:43

  class  ObjectAttributeDataReader
    : public virtual ::OpenDDS::DCPS::DataReaderEx
  
  {
  public:

    // TAO_IDL - Generated from
    // e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_type.cpp:307

    typedef ObjectAttributeDataReader_ptr _ptr_type;
    typedef ObjectAttributeDataReader_var _var_type;
    typedef ObjectAttributeDataReader_out _out_type;

    // The static operations.
    static ObjectAttributeDataReader_ptr _duplicate (ObjectAttributeDataReader_ptr obj);

    static void _tao_release (ObjectAttributeDataReader_ptr obj);

    static ObjectAttributeDataReader_ptr _narrow (::CORBA::Object_ptr obj);
    static ObjectAttributeDataReader_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static ObjectAttributeDataReader_ptr _nil (void);

    virtual ::DDS::ReturnCode_t read (
      ::Data_Exchange_Platform::ObjectAttributeSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take (
      ::Data_Exchange_Platform::ObjectAttributeSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_w_condition (
      ::Data_Exchange_Platform::ObjectAttributeSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_w_condition (
      ::Data_Exchange_Platform::ObjectAttributeSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_sample (
      ::Data_Exchange_Platform::ObjectAttribute & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t take_next_sample (
      ::Data_Exchange_Platform::ObjectAttribute & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t read_instance (
      ::Data_Exchange_Platform::ObjectAttributeSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_instance (
      ::Data_Exchange_Platform::ObjectAttributeSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_instance_w_condition (
      ::Data_Exchange_Platform::ObjectAttributeSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_instance_w_condition (
      ::Data_Exchange_Platform::ObjectAttributeSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance (
      ::Data_Exchange_Platform::ObjectAttributeSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance (
      ::Data_Exchange_Platform::ObjectAttributeSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance_w_condition (
      ::Data_Exchange_Platform::ObjectAttributeSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance_w_condition (
      ::Data_Exchange_Platform::ObjectAttributeSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t return_loan (
      ::Data_Exchange_Platform::ObjectAttributeSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::Data_Exchange_Platform::ObjectAttribute & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::Data_Exchange_Platform::ObjectAttribute & instance_data) = 0;

    // TAO_IDL - Generated from
    // e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    ObjectAttributeDataReader (void);

    

    virtual ~ObjectAttributeDataReader (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    ObjectAttributeDataReader (const ObjectAttributeDataReader &);

    void operator= (const ObjectAttributeDataReader &);
  };

// TAO_IDL - Generated from
// e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_visitor_module\module_ch.cpp:67

} // module Data_Exchange_Platform

// TAO_IDL - Generated from
// e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_visitor_module\module_ch.cpp:38

namespace Data_Exchange_Platform
{

  // TAO_IDL - Generated from
  // e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_visitor_sequence\sequence_ch.cpp:102

  typedef ::TAO::DCPS::ZeroCopyDataSeq< Data_Exchange_Platform::InterationParameter, DCPS_ZERO_COPY_SEQ_DEFAULT_SIZE> InterationParameterSeq;
  

  // TAO_IDL - Generated from
  // e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_interface.cpp:751

#if !defined (_DATA_EXCHANGE_PLATFORM_INTERATIONPARAMETERTYPESUPPORT__VAR_OUT_CH_)
#define _DATA_EXCHANGE_PLATFORM_INTERATIONPARAMETERTYPESUPPORT__VAR_OUT_CH_

  class InterationParameterTypeSupport;
  typedef InterationParameterTypeSupport *InterationParameterTypeSupport_ptr;

  typedef
    TAO_Objref_Var_T<
        InterationParameterTypeSupport
      >
    InterationParameterTypeSupport_var;
  
  typedef
    TAO_Objref_Out_T<
        InterationParameterTypeSupport
      >
    InterationParameterTypeSupport_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:43

  class  InterationParameterTypeSupport
    : public virtual ::OpenDDS::DCPS::TypeSupport
  
  {
  public:

    // TAO_IDL - Generated from
    // e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_type.cpp:307

    typedef InterationParameterTypeSupport_ptr _ptr_type;
    typedef InterationParameterTypeSupport_var _var_type;
    typedef InterationParameterTypeSupport_out _out_type;

    // The static operations.
    static InterationParameterTypeSupport_ptr _duplicate (InterationParameterTypeSupport_ptr obj);

    static void _tao_release (InterationParameterTypeSupport_ptr obj);

    static InterationParameterTypeSupport_ptr _narrow (::CORBA::Object_ptr obj);
    static InterationParameterTypeSupport_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static InterationParameterTypeSupport_ptr _nil (void);

    // TAO_IDL - Generated from
    // e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    InterationParameterTypeSupport (void);

    

    virtual ~InterationParameterTypeSupport (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    InterationParameterTypeSupport (const InterationParameterTypeSupport &);

    void operator= (const InterationParameterTypeSupport &);
  };

  // TAO_IDL - Generated from
  // e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_interface.cpp:751

#if !defined (_DATA_EXCHANGE_PLATFORM_INTERATIONPARAMETERDATAWRITER__VAR_OUT_CH_)
#define _DATA_EXCHANGE_PLATFORM_INTERATIONPARAMETERDATAWRITER__VAR_OUT_CH_

  class InterationParameterDataWriter;
  typedef InterationParameterDataWriter *InterationParameterDataWriter_ptr;

  typedef
    TAO_Objref_Var_T<
        InterationParameterDataWriter
      >
    InterationParameterDataWriter_var;
  
  typedef
    TAO_Objref_Out_T<
        InterationParameterDataWriter
      >
    InterationParameterDataWriter_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:43

  class  InterationParameterDataWriter
    : public virtual ::DDS::DataWriter
  
  {
  public:

    // TAO_IDL - Generated from
    // e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_type.cpp:307

    typedef InterationParameterDataWriter_ptr _ptr_type;
    typedef InterationParameterDataWriter_var _var_type;
    typedef InterationParameterDataWriter_out _out_type;

    // The static operations.
    static InterationParameterDataWriter_ptr _duplicate (InterationParameterDataWriter_ptr obj);

    static void _tao_release (InterationParameterDataWriter_ptr obj);

    static InterationParameterDataWriter_ptr _narrow (::CORBA::Object_ptr obj);
    static InterationParameterDataWriter_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static InterationParameterDataWriter_ptr _nil (void);

    virtual ::DDS::InstanceHandle_t register_instance (
      const ::Data_Exchange_Platform::InterationParameter & instance) = 0;

    virtual ::DDS::InstanceHandle_t register_instance_w_timestamp (
      const ::Data_Exchange_Platform::InterationParameter & instance,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance (
      const ::Data_Exchange_Platform::InterationParameter & instance,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance_w_timestamp (
      const ::Data_Exchange_Platform::InterationParameter & instance,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t write (
      const ::Data_Exchange_Platform::InterationParameter & instance_data,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t write_w_timestamp (
      const ::Data_Exchange_Platform::InterationParameter & instance_data,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t dispose (
      const ::Data_Exchange_Platform::InterationParameter & instance_data,
      ::DDS::InstanceHandle_t instance_handle) = 0;

    virtual ::DDS::ReturnCode_t dispose_w_timestamp (
      const ::Data_Exchange_Platform::InterationParameter & instance_data,
      ::DDS::InstanceHandle_t instance_handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::Data_Exchange_Platform::InterationParameter & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::Data_Exchange_Platform::InterationParameter & instance_data) = 0;

    // TAO_IDL - Generated from
    // e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    InterationParameterDataWriter (void);

    

    virtual ~InterationParameterDataWriter (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    InterationParameterDataWriter (const InterationParameterDataWriter &);

    void operator= (const InterationParameterDataWriter &);
  };

  // TAO_IDL - Generated from
  // e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_interface.cpp:751

#if !defined (_DATA_EXCHANGE_PLATFORM_INTERATIONPARAMETERDATAREADER__VAR_OUT_CH_)
#define _DATA_EXCHANGE_PLATFORM_INTERATIONPARAMETERDATAREADER__VAR_OUT_CH_

  class InterationParameterDataReader;
  typedef InterationParameterDataReader *InterationParameterDataReader_ptr;

  typedef
    TAO_Objref_Var_T<
        InterationParameterDataReader
      >
    InterationParameterDataReader_var;
  
  typedef
    TAO_Objref_Out_T<
        InterationParameterDataReader
      >
    InterationParameterDataReader_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:43

  class  InterationParameterDataReader
    : public virtual ::OpenDDS::DCPS::DataReaderEx
  
  {
  public:

    // TAO_IDL - Generated from
    // e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_type.cpp:307

    typedef InterationParameterDataReader_ptr _ptr_type;
    typedef InterationParameterDataReader_var _var_type;
    typedef InterationParameterDataReader_out _out_type;

    // The static operations.
    static InterationParameterDataReader_ptr _duplicate (InterationParameterDataReader_ptr obj);

    static void _tao_release (InterationParameterDataReader_ptr obj);

    static InterationParameterDataReader_ptr _narrow (::CORBA::Object_ptr obj);
    static InterationParameterDataReader_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static InterationParameterDataReader_ptr _nil (void);

    virtual ::DDS::ReturnCode_t read (
      ::Data_Exchange_Platform::InterationParameterSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take (
      ::Data_Exchange_Platform::InterationParameterSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_w_condition (
      ::Data_Exchange_Platform::InterationParameterSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_w_condition (
      ::Data_Exchange_Platform::InterationParameterSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_sample (
      ::Data_Exchange_Platform::InterationParameter & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t take_next_sample (
      ::Data_Exchange_Platform::InterationParameter & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t read_instance (
      ::Data_Exchange_Platform::InterationParameterSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_instance (
      ::Data_Exchange_Platform::InterationParameterSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_instance_w_condition (
      ::Data_Exchange_Platform::InterationParameterSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_instance_w_condition (
      ::Data_Exchange_Platform::InterationParameterSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance (
      ::Data_Exchange_Platform::InterationParameterSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance (
      ::Data_Exchange_Platform::InterationParameterSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance_w_condition (
      ::Data_Exchange_Platform::InterationParameterSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance_w_condition (
      ::Data_Exchange_Platform::InterationParameterSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t return_loan (
      ::Data_Exchange_Platform::InterationParameterSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::Data_Exchange_Platform::InterationParameter & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::Data_Exchange_Platform::InterationParameter & instance_data) = 0;

    // TAO_IDL - Generated from
    // e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    InterationParameterDataReader (void);

    

    virtual ~InterationParameterDataReader (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    InterationParameterDataReader (const InterationParameterDataReader &);

    void operator= (const InterationParameterDataReader &);
  };

// TAO_IDL - Generated from
// e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_visitor_module\module_ch.cpp:67

} // module Data_Exchange_Platform

// TAO_IDL - Generated from
// e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_visitor_module\module_ch.cpp:38

namespace Data_Exchange_Platform
{

  // TAO_IDL - Generated from
  // e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_visitor_sequence\sequence_ch.cpp:102

  typedef ::TAO::DCPS::ZeroCopyDataSeq< Data_Exchange_Platform::Interation, DCPS_ZERO_COPY_SEQ_DEFAULT_SIZE> InterationSeq;
  

  // TAO_IDL - Generated from
  // e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_interface.cpp:751

#if !defined (_DATA_EXCHANGE_PLATFORM_INTERATIONTYPESUPPORT__VAR_OUT_CH_)
#define _DATA_EXCHANGE_PLATFORM_INTERATIONTYPESUPPORT__VAR_OUT_CH_

  class InterationTypeSupport;
  typedef InterationTypeSupport *InterationTypeSupport_ptr;

  typedef
    TAO_Objref_Var_T<
        InterationTypeSupport
      >
    InterationTypeSupport_var;
  
  typedef
    TAO_Objref_Out_T<
        InterationTypeSupport
      >
    InterationTypeSupport_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:43

  class  InterationTypeSupport
    : public virtual ::OpenDDS::DCPS::TypeSupport
  
  {
  public:

    // TAO_IDL - Generated from
    // e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_type.cpp:307

    typedef InterationTypeSupport_ptr _ptr_type;
    typedef InterationTypeSupport_var _var_type;
    typedef InterationTypeSupport_out _out_type;

    // The static operations.
    static InterationTypeSupport_ptr _duplicate (InterationTypeSupport_ptr obj);

    static void _tao_release (InterationTypeSupport_ptr obj);

    static InterationTypeSupport_ptr _narrow (::CORBA::Object_ptr obj);
    static InterationTypeSupport_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static InterationTypeSupport_ptr _nil (void);

    // TAO_IDL - Generated from
    // e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    InterationTypeSupport (void);

    

    virtual ~InterationTypeSupport (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    InterationTypeSupport (const InterationTypeSupport &);

    void operator= (const InterationTypeSupport &);
  };

  // TAO_IDL - Generated from
  // e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_interface.cpp:751

#if !defined (_DATA_EXCHANGE_PLATFORM_INTERATIONDATAWRITER__VAR_OUT_CH_)
#define _DATA_EXCHANGE_PLATFORM_INTERATIONDATAWRITER__VAR_OUT_CH_

  class InterationDataWriter;
  typedef InterationDataWriter *InterationDataWriter_ptr;

  typedef
    TAO_Objref_Var_T<
        InterationDataWriter
      >
    InterationDataWriter_var;
  
  typedef
    TAO_Objref_Out_T<
        InterationDataWriter
      >
    InterationDataWriter_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:43

  class  InterationDataWriter
    : public virtual ::DDS::DataWriter
  
  {
  public:

    // TAO_IDL - Generated from
    // e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_type.cpp:307

    typedef InterationDataWriter_ptr _ptr_type;
    typedef InterationDataWriter_var _var_type;
    typedef InterationDataWriter_out _out_type;

    // The static operations.
    static InterationDataWriter_ptr _duplicate (InterationDataWriter_ptr obj);

    static void _tao_release (InterationDataWriter_ptr obj);

    static InterationDataWriter_ptr _narrow (::CORBA::Object_ptr obj);
    static InterationDataWriter_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static InterationDataWriter_ptr _nil (void);

    virtual ::DDS::InstanceHandle_t register_instance (
      const ::Data_Exchange_Platform::Interation & instance) = 0;

    virtual ::DDS::InstanceHandle_t register_instance_w_timestamp (
      const ::Data_Exchange_Platform::Interation & instance,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance (
      const ::Data_Exchange_Platform::Interation & instance,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance_w_timestamp (
      const ::Data_Exchange_Platform::Interation & instance,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t write (
      const ::Data_Exchange_Platform::Interation & instance_data,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t write_w_timestamp (
      const ::Data_Exchange_Platform::Interation & instance_data,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t dispose (
      const ::Data_Exchange_Platform::Interation & instance_data,
      ::DDS::InstanceHandle_t instance_handle) = 0;

    virtual ::DDS::ReturnCode_t dispose_w_timestamp (
      const ::Data_Exchange_Platform::Interation & instance_data,
      ::DDS::InstanceHandle_t instance_handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::Data_Exchange_Platform::Interation & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::Data_Exchange_Platform::Interation & instance_data) = 0;

    // TAO_IDL - Generated from
    // e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    InterationDataWriter (void);

    

    virtual ~InterationDataWriter (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    InterationDataWriter (const InterationDataWriter &);

    void operator= (const InterationDataWriter &);
  };

  // TAO_IDL - Generated from
  // e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_interface.cpp:751

#if !defined (_DATA_EXCHANGE_PLATFORM_INTERATIONDATAREADER__VAR_OUT_CH_)
#define _DATA_EXCHANGE_PLATFORM_INTERATIONDATAREADER__VAR_OUT_CH_

  class InterationDataReader;
  typedef InterationDataReader *InterationDataReader_ptr;

  typedef
    TAO_Objref_Var_T<
        InterationDataReader
      >
    InterationDataReader_var;
  
  typedef
    TAO_Objref_Out_T<
        InterationDataReader
      >
    InterationDataReader_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:43

  class  InterationDataReader
    : public virtual ::OpenDDS::DCPS::DataReaderEx
  
  {
  public:

    // TAO_IDL - Generated from
    // e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_type.cpp:307

    typedef InterationDataReader_ptr _ptr_type;
    typedef InterationDataReader_var _var_type;
    typedef InterationDataReader_out _out_type;

    // The static operations.
    static InterationDataReader_ptr _duplicate (InterationDataReader_ptr obj);

    static void _tao_release (InterationDataReader_ptr obj);

    static InterationDataReader_ptr _narrow (::CORBA::Object_ptr obj);
    static InterationDataReader_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static InterationDataReader_ptr _nil (void);

    virtual ::DDS::ReturnCode_t read (
      ::Data_Exchange_Platform::InterationSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take (
      ::Data_Exchange_Platform::InterationSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_w_condition (
      ::Data_Exchange_Platform::InterationSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_w_condition (
      ::Data_Exchange_Platform::InterationSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_sample (
      ::Data_Exchange_Platform::Interation & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t take_next_sample (
      ::Data_Exchange_Platform::Interation & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t read_instance (
      ::Data_Exchange_Platform::InterationSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_instance (
      ::Data_Exchange_Platform::InterationSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_instance_w_condition (
      ::Data_Exchange_Platform::InterationSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_instance_w_condition (
      ::Data_Exchange_Platform::InterationSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance (
      ::Data_Exchange_Platform::InterationSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance (
      ::Data_Exchange_Platform::InterationSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance_w_condition (
      ::Data_Exchange_Platform::InterationSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance_w_condition (
      ::Data_Exchange_Platform::InterationSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t return_loan (
      ::Data_Exchange_Platform::InterationSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::Data_Exchange_Platform::Interation & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::Data_Exchange_Platform::Interation & instance_data) = 0;

    // TAO_IDL - Generated from
    // e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    InterationDataReader (void);

    

    virtual ~InterationDataReader (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    InterationDataReader (const InterationDataReader &);

    void operator= (const InterationDataReader &);
  };

// TAO_IDL - Generated from
// e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_visitor_module\module_ch.cpp:67

} // module Data_Exchange_Platform

// TAO_IDL - Generated from
// e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_visitor_module\module_ch.cpp:38

namespace Data_Exchange_Platform
{

  // TAO_IDL - Generated from
  // e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_visitor_sequence\sequence_ch.cpp:102

  typedef ::TAO::DCPS::ZeroCopyDataSeq< Data_Exchange_Platform::Interations, DCPS_ZERO_COPY_SEQ_DEFAULT_SIZE> InterationsSeq;
  

  // TAO_IDL - Generated from
  // e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_interface.cpp:751

#if !defined (_DATA_EXCHANGE_PLATFORM_INTERATIONSTYPESUPPORT__VAR_OUT_CH_)
#define _DATA_EXCHANGE_PLATFORM_INTERATIONSTYPESUPPORT__VAR_OUT_CH_

  class InterationsTypeSupport;
  typedef InterationsTypeSupport *InterationsTypeSupport_ptr;

  typedef
    TAO_Objref_Var_T<
        InterationsTypeSupport
      >
    InterationsTypeSupport_var;
  
  typedef
    TAO_Objref_Out_T<
        InterationsTypeSupport
      >
    InterationsTypeSupport_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:43

  class  InterationsTypeSupport
    : public virtual ::OpenDDS::DCPS::TypeSupport
  
  {
  public:

    // TAO_IDL - Generated from
    // e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_type.cpp:307

    typedef InterationsTypeSupport_ptr _ptr_type;
    typedef InterationsTypeSupport_var _var_type;
    typedef InterationsTypeSupport_out _out_type;

    // The static operations.
    static InterationsTypeSupport_ptr _duplicate (InterationsTypeSupport_ptr obj);

    static void _tao_release (InterationsTypeSupport_ptr obj);

    static InterationsTypeSupport_ptr _narrow (::CORBA::Object_ptr obj);
    static InterationsTypeSupport_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static InterationsTypeSupport_ptr _nil (void);

    // TAO_IDL - Generated from
    // e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    InterationsTypeSupport (void);

    

    virtual ~InterationsTypeSupport (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    InterationsTypeSupport (const InterationsTypeSupport &);

    void operator= (const InterationsTypeSupport &);
  };

  // TAO_IDL - Generated from
  // e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_interface.cpp:751

#if !defined (_DATA_EXCHANGE_PLATFORM_INTERATIONSDATAWRITER__VAR_OUT_CH_)
#define _DATA_EXCHANGE_PLATFORM_INTERATIONSDATAWRITER__VAR_OUT_CH_

  class InterationsDataWriter;
  typedef InterationsDataWriter *InterationsDataWriter_ptr;

  typedef
    TAO_Objref_Var_T<
        InterationsDataWriter
      >
    InterationsDataWriter_var;
  
  typedef
    TAO_Objref_Out_T<
        InterationsDataWriter
      >
    InterationsDataWriter_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:43

  class  InterationsDataWriter
    : public virtual ::DDS::DataWriter
  
  {
  public:

    // TAO_IDL - Generated from
    // e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_type.cpp:307

    typedef InterationsDataWriter_ptr _ptr_type;
    typedef InterationsDataWriter_var _var_type;
    typedef InterationsDataWriter_out _out_type;

    // The static operations.
    static InterationsDataWriter_ptr _duplicate (InterationsDataWriter_ptr obj);

    static void _tao_release (InterationsDataWriter_ptr obj);

    static InterationsDataWriter_ptr _narrow (::CORBA::Object_ptr obj);
    static InterationsDataWriter_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static InterationsDataWriter_ptr _nil (void);

    virtual ::DDS::InstanceHandle_t register_instance (
      const ::Data_Exchange_Platform::Interations & instance) = 0;

    virtual ::DDS::InstanceHandle_t register_instance_w_timestamp (
      const ::Data_Exchange_Platform::Interations & instance,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance (
      const ::Data_Exchange_Platform::Interations & instance,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance_w_timestamp (
      const ::Data_Exchange_Platform::Interations & instance,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t write (
      const ::Data_Exchange_Platform::Interations & instance_data,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t write_w_timestamp (
      const ::Data_Exchange_Platform::Interations & instance_data,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t dispose (
      const ::Data_Exchange_Platform::Interations & instance_data,
      ::DDS::InstanceHandle_t instance_handle) = 0;

    virtual ::DDS::ReturnCode_t dispose_w_timestamp (
      const ::Data_Exchange_Platform::Interations & instance_data,
      ::DDS::InstanceHandle_t instance_handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::Data_Exchange_Platform::Interations & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::Data_Exchange_Platform::Interations & instance_data) = 0;

    // TAO_IDL - Generated from
    // e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    InterationsDataWriter (void);

    

    virtual ~InterationsDataWriter (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    InterationsDataWriter (const InterationsDataWriter &);

    void operator= (const InterationsDataWriter &);
  };

  // TAO_IDL - Generated from
  // e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_interface.cpp:751

#if !defined (_DATA_EXCHANGE_PLATFORM_INTERATIONSDATAREADER__VAR_OUT_CH_)
#define _DATA_EXCHANGE_PLATFORM_INTERATIONSDATAREADER__VAR_OUT_CH_

  class InterationsDataReader;
  typedef InterationsDataReader *InterationsDataReader_ptr;

  typedef
    TAO_Objref_Var_T<
        InterationsDataReader
      >
    InterationsDataReader_var;
  
  typedef
    TAO_Objref_Out_T<
        InterationsDataReader
      >
    InterationsDataReader_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:43

  class  InterationsDataReader
    : public virtual ::OpenDDS::DCPS::DataReaderEx
  
  {
  public:

    // TAO_IDL - Generated from
    // e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_type.cpp:307

    typedef InterationsDataReader_ptr _ptr_type;
    typedef InterationsDataReader_var _var_type;
    typedef InterationsDataReader_out _out_type;

    // The static operations.
    static InterationsDataReader_ptr _duplicate (InterationsDataReader_ptr obj);

    static void _tao_release (InterationsDataReader_ptr obj);

    static InterationsDataReader_ptr _narrow (::CORBA::Object_ptr obj);
    static InterationsDataReader_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static InterationsDataReader_ptr _nil (void);

    virtual ::DDS::ReturnCode_t read (
      ::Data_Exchange_Platform::InterationsSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take (
      ::Data_Exchange_Platform::InterationsSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_w_condition (
      ::Data_Exchange_Platform::InterationsSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_w_condition (
      ::Data_Exchange_Platform::InterationsSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_sample (
      ::Data_Exchange_Platform::Interations & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t take_next_sample (
      ::Data_Exchange_Platform::Interations & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t read_instance (
      ::Data_Exchange_Platform::InterationsSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_instance (
      ::Data_Exchange_Platform::InterationsSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_instance_w_condition (
      ::Data_Exchange_Platform::InterationsSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_instance_w_condition (
      ::Data_Exchange_Platform::InterationsSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance (
      ::Data_Exchange_Platform::InterationsSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance (
      ::Data_Exchange_Platform::InterationsSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance_w_condition (
      ::Data_Exchange_Platform::InterationsSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance_w_condition (
      ::Data_Exchange_Platform::InterationsSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t return_loan (
      ::Data_Exchange_Platform::InterationsSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::Data_Exchange_Platform::Interations & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::Data_Exchange_Platform::Interations & instance_data) = 0;

    // TAO_IDL - Generated from
    // e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    InterationsDataReader (void);

    

    virtual ~InterationsDataReader (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    InterationsDataReader (const InterationsDataReader &);

    void operator= (const InterationsDataReader &);
  };

// TAO_IDL - Generated from
// e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_visitor_module\module_ch.cpp:67

} // module Data_Exchange_Platform

// TAO_IDL - Generated from
// e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_visitor_arg_traits.cpp:68

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_visitor_traits.cpp:62

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{

#if !defined (_DATA_EXCHANGE_PLATFORM_OBJECTATTRIBUTETYPESUPPORT__TRAITS_)
#define _DATA_EXCHANGE_PLATFORM_OBJECTATTRIBUTETYPESUPPORT__TRAITS_

  template<>
  struct  Objref_Traits< ::Data_Exchange_Platform::ObjectAttributeTypeSupport>
  {
    static ::Data_Exchange_Platform::ObjectAttributeTypeSupport_ptr duplicate (
        ::Data_Exchange_Platform::ObjectAttributeTypeSupport_ptr p);
    static void release (
        ::Data_Exchange_Platform::ObjectAttributeTypeSupport_ptr p);
    static ::Data_Exchange_Platform::ObjectAttributeTypeSupport_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::Data_Exchange_Platform::ObjectAttributeTypeSupport_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_DATA_EXCHANGE_PLATFORM_OBJECTATTRIBUTEDATAWRITER__TRAITS_)
#define _DATA_EXCHANGE_PLATFORM_OBJECTATTRIBUTEDATAWRITER__TRAITS_

  template<>
  struct  Objref_Traits< ::Data_Exchange_Platform::ObjectAttributeDataWriter>
  {
    static ::Data_Exchange_Platform::ObjectAttributeDataWriter_ptr duplicate (
        ::Data_Exchange_Platform::ObjectAttributeDataWriter_ptr p);
    static void release (
        ::Data_Exchange_Platform::ObjectAttributeDataWriter_ptr p);
    static ::Data_Exchange_Platform::ObjectAttributeDataWriter_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::Data_Exchange_Platform::ObjectAttributeDataWriter_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_DATA_EXCHANGE_PLATFORM_OBJECTATTRIBUTEDATAREADER__TRAITS_)
#define _DATA_EXCHANGE_PLATFORM_OBJECTATTRIBUTEDATAREADER__TRAITS_

  template<>
  struct  Objref_Traits< ::Data_Exchange_Platform::ObjectAttributeDataReader>
  {
    static ::Data_Exchange_Platform::ObjectAttributeDataReader_ptr duplicate (
        ::Data_Exchange_Platform::ObjectAttributeDataReader_ptr p);
    static void release (
        ::Data_Exchange_Platform::ObjectAttributeDataReader_ptr p);
    static ::Data_Exchange_Platform::ObjectAttributeDataReader_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::Data_Exchange_Platform::ObjectAttributeDataReader_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_DATA_EXCHANGE_PLATFORM_INTERATIONPARAMETERTYPESUPPORT__TRAITS_)
#define _DATA_EXCHANGE_PLATFORM_INTERATIONPARAMETERTYPESUPPORT__TRAITS_

  template<>
  struct  Objref_Traits< ::Data_Exchange_Platform::InterationParameterTypeSupport>
  {
    static ::Data_Exchange_Platform::InterationParameterTypeSupport_ptr duplicate (
        ::Data_Exchange_Platform::InterationParameterTypeSupport_ptr p);
    static void release (
        ::Data_Exchange_Platform::InterationParameterTypeSupport_ptr p);
    static ::Data_Exchange_Platform::InterationParameterTypeSupport_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::Data_Exchange_Platform::InterationParameterTypeSupport_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_DATA_EXCHANGE_PLATFORM_INTERATIONPARAMETERDATAWRITER__TRAITS_)
#define _DATA_EXCHANGE_PLATFORM_INTERATIONPARAMETERDATAWRITER__TRAITS_

  template<>
  struct  Objref_Traits< ::Data_Exchange_Platform::InterationParameterDataWriter>
  {
    static ::Data_Exchange_Platform::InterationParameterDataWriter_ptr duplicate (
        ::Data_Exchange_Platform::InterationParameterDataWriter_ptr p);
    static void release (
        ::Data_Exchange_Platform::InterationParameterDataWriter_ptr p);
    static ::Data_Exchange_Platform::InterationParameterDataWriter_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::Data_Exchange_Platform::InterationParameterDataWriter_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_DATA_EXCHANGE_PLATFORM_INTERATIONPARAMETERDATAREADER__TRAITS_)
#define _DATA_EXCHANGE_PLATFORM_INTERATIONPARAMETERDATAREADER__TRAITS_

  template<>
  struct  Objref_Traits< ::Data_Exchange_Platform::InterationParameterDataReader>
  {
    static ::Data_Exchange_Platform::InterationParameterDataReader_ptr duplicate (
        ::Data_Exchange_Platform::InterationParameterDataReader_ptr p);
    static void release (
        ::Data_Exchange_Platform::InterationParameterDataReader_ptr p);
    static ::Data_Exchange_Platform::InterationParameterDataReader_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::Data_Exchange_Platform::InterationParameterDataReader_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_DATA_EXCHANGE_PLATFORM_INTERATIONTYPESUPPORT__TRAITS_)
#define _DATA_EXCHANGE_PLATFORM_INTERATIONTYPESUPPORT__TRAITS_

  template<>
  struct  Objref_Traits< ::Data_Exchange_Platform::InterationTypeSupport>
  {
    static ::Data_Exchange_Platform::InterationTypeSupport_ptr duplicate (
        ::Data_Exchange_Platform::InterationTypeSupport_ptr p);
    static void release (
        ::Data_Exchange_Platform::InterationTypeSupport_ptr p);
    static ::Data_Exchange_Platform::InterationTypeSupport_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::Data_Exchange_Platform::InterationTypeSupport_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_DATA_EXCHANGE_PLATFORM_INTERATIONDATAWRITER__TRAITS_)
#define _DATA_EXCHANGE_PLATFORM_INTERATIONDATAWRITER__TRAITS_

  template<>
  struct  Objref_Traits< ::Data_Exchange_Platform::InterationDataWriter>
  {
    static ::Data_Exchange_Platform::InterationDataWriter_ptr duplicate (
        ::Data_Exchange_Platform::InterationDataWriter_ptr p);
    static void release (
        ::Data_Exchange_Platform::InterationDataWriter_ptr p);
    static ::Data_Exchange_Platform::InterationDataWriter_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::Data_Exchange_Platform::InterationDataWriter_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_DATA_EXCHANGE_PLATFORM_INTERATIONDATAREADER__TRAITS_)
#define _DATA_EXCHANGE_PLATFORM_INTERATIONDATAREADER__TRAITS_

  template<>
  struct  Objref_Traits< ::Data_Exchange_Platform::InterationDataReader>
  {
    static ::Data_Exchange_Platform::InterationDataReader_ptr duplicate (
        ::Data_Exchange_Platform::InterationDataReader_ptr p);
    static void release (
        ::Data_Exchange_Platform::InterationDataReader_ptr p);
    static ::Data_Exchange_Platform::InterationDataReader_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::Data_Exchange_Platform::InterationDataReader_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_DATA_EXCHANGE_PLATFORM_INTERATIONSTYPESUPPORT__TRAITS_)
#define _DATA_EXCHANGE_PLATFORM_INTERATIONSTYPESUPPORT__TRAITS_

  template<>
  struct  Objref_Traits< ::Data_Exchange_Platform::InterationsTypeSupport>
  {
    static ::Data_Exchange_Platform::InterationsTypeSupport_ptr duplicate (
        ::Data_Exchange_Platform::InterationsTypeSupport_ptr p);
    static void release (
        ::Data_Exchange_Platform::InterationsTypeSupport_ptr p);
    static ::Data_Exchange_Platform::InterationsTypeSupport_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::Data_Exchange_Platform::InterationsTypeSupport_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_DATA_EXCHANGE_PLATFORM_INTERATIONSDATAWRITER__TRAITS_)
#define _DATA_EXCHANGE_PLATFORM_INTERATIONSDATAWRITER__TRAITS_

  template<>
  struct  Objref_Traits< ::Data_Exchange_Platform::InterationsDataWriter>
  {
    static ::Data_Exchange_Platform::InterationsDataWriter_ptr duplicate (
        ::Data_Exchange_Platform::InterationsDataWriter_ptr p);
    static void release (
        ::Data_Exchange_Platform::InterationsDataWriter_ptr p);
    static ::Data_Exchange_Platform::InterationsDataWriter_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::Data_Exchange_Platform::InterationsDataWriter_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_DATA_EXCHANGE_PLATFORM_INTERATIONSDATAREADER__TRAITS_)
#define _DATA_EXCHANGE_PLATFORM_INTERATIONSDATAREADER__TRAITS_

  template<>
  struct  Objref_Traits< ::Data_Exchange_Platform::InterationsDataReader>
  {
    static ::Data_Exchange_Platform::InterationsDataReader_ptr duplicate (
        ::Data_Exchange_Platform::InterationsDataReader_ptr p);
    static void release (
        ::Data_Exchange_Platform::InterationsDataReader_ptr p);
    static ::Data_Exchange_Platform::InterationsDataReader_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::Data_Exchange_Platform::InterationsDataReader_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// e:\opendds-3.12\ace_wrappers\tao\tao_idl\be\be_codegen.cpp:1703
#if defined (__ACE_INLINE__)
#include "DataExchangeTypeSupportC.inl"
#endif /* defined INLINE */

#include /**/ "ace/post.h"

#endif /* ifndef */

